### PR TITLE
Add blank lines after semicolons

### PR DESCRIPTION
**Pull request by macintoshpie**
## background
The formatter currently doesn't add any empty lines between code making it less readable (see #32 )

## changes
- insert a blank line after every semicolon, with some exceptions (`within` statement, inside `[]` brackets)

Thanks to @trivvz for doing most of the work!

### CODE REVIEW

**Review by nllong — APPROVED** [review]
Looks dandy to me! ⚡️

**Comment by macintoshpie** [comment]
@mwetter @AntoineGautier any reservations about this change?

**Comment by mwetter** [comment]
Can we suppress these empty lines in the equation section (and the initial equation, algorithm and initial algorithm) section? 
I think these sections are well readable in editors that have syntax coloring, and having all these spaces just takes away what can be seen on one screen.
In the declaration section (above the initial equation section), I am fine with the change, although for `parameter` and `constant` declarations I would prefer not adding spaces in between, because these are often only one or two lines long.
Having spaces between the generally longer instantiation clauses of objects make the file more readable.

This probably also addresses item 2 in https://github.com/urbanopt/modelica-fmt/issues/26

**Comment by tpwo** [comment]
@mwetter, yeah, I agree that adding blank lines between all single line statements is a bit of space waste.

I think that the ideal approach would be to allow both for zero and single blank line space between one-liners (sometimes it's good to split some groups of single-line equations etc from each other). But that means reading this information during parsing and saving it for later use.

A simpler solution for now: maybe just insert blank lines only before and after multiline statements no matter where they are?

With the current formatting output, parameters/constants with annotations are also multiline, though. But TBH, I would still prefer a blank line between them in this situation.

Regarding the implementation, I see that it would still be possible to see a blank line after singleline statement if the next one is multiline:

```
singleline;
singleline;

multiline
multiline;

multiline
multiline
multiline;

singleline;
```

**Comment by mwetter** [comment]
@trivvz : I looked at a few files and think empty lines are most useful if the code switches between sections that have different declarations, e.g., after all `parameters`, before `protected`, before `equation`, before `//` (comments), etc.

Looking at files such as https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/BoundaryConditions/SolarIrradiation/DiffusePerez.mo
I think syntax coloring makes them good readable without these extra empty lines, and adding many empty lines just reduces what one can see on the screen.

**Comment by macintoshpie** [comment]
Hmm, maybe just make this optional for now as a "beta" feature until we find a more generally satisfying solution. I can get those changes up soon.

Regarding a more general fix, maybe we should tokenize empty lines and store them like we do comments, then use that to determine if/where to insert empty lines - allowing users to "keep" their lines if they want to. Maybe do something like black's rules around empty lines: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#empty-lines

**Pull request merged**
